Repository acstech/doppler-frontend, pull requests merged in 2018-06, with the labels that each got.

#42 Added the README
  README.md
Labels: enhancement

#45 Updated the js files
  About/About.html
  Assets/images/Fire_Emoji_large.png
  Assets/images/logo.png
  Assets/images/monkimage.png
  Assets/js/map.js
  Assets/js/modal.js
  index.html
  tests/main.go
Labels: design, enhancement

#48 This is updated front-end with working Map Reset
  Assets/CSS/Heatmap.css
  Assets/js/map.js
  index.html
Labels: design, enhancement

#60 Got the reset view button to work
  Assets/CSS/Heatmap.css
  Assets/images/Fire_Emoji_large.png
  Assets/js/animation.js
  Assets/js/map.js
  index.html
Labels: design, enhancement

#65 Peterk/all btn
  Assets/CSS/Heatmap.css
  Assets/js/animation.js
  Assets/js/map.js
  Assets/js/modal.js
  index.html
Labels: design, enhancement

#73 added the slider to the menu bar, as well as align the buttons
  Assets/CSS/Heatmap.css
  Assets/js/animation.js
  Assets/js/datapoints.js
  Assets/js/map.js
  index.html
Labels: design, enhancement

#74 updated the list of events
  Assets/CSS/Heatmap.css
  Assets/js/animation.js
  Assets/js/modal.js
  Assets/js/setUpWS.js
  index.html
Labels: design, enhancement

#81 got the menu bar working with JQuery plugin, changed sidebar's format
  Assets/CSS/Heatmap.css
  Assets/js/animation.js
  Assets/js/jquery.slidereveal.min.js
  index.html
Labels: MVP, design, enhancement

#84 updated error handling
  Assets/js/setUpWS.js
Labels: MVP, enhancement

#85 Added fix for client sign in bug
  Assets/js/setUpWS.js
  index.html
Labels: MVP, bug, enhancement

#89 Updated how filters are displayed.
  Assets/CSS/Heatmap.css
  Assets/js/setUpWS.js
  index.html
Labels: MVP, bug, design, enhancement

#91 MattH/sidebar color
  Assets/CSS/Heatmap.css
  Assets/js/animation.js
  Assets/js/map.js
  Assets/js/modal.js
  Assets/js/setUpWS.js
  index.html
Labels: MVP, design, enhancement, needs testing

#95 Error handling
  Assets/js/modal.js
  Assets/js/setUpWS.js
  index.html
Labels: MVP, design, enhancement, needs testing

#98 Added the decay function and the ability to take in bucketed data.
  Assets/js/animation.js
  Assets/js/leaflet-heatmap.js
  Assets/js/map.js
  Assets/js/setUpWS.js
Labels: MVP, enhancement
